### PR TITLE
yaap: Track NQ NXP repositories from LineageOS

### PR DESCRIPTION
**Pull request by ALKALiKong233**

### CODE REVIEW

**Comment by ALKALiKong233** [comment]
I'm not sure who to request to review lol
Sorry if disturbed

**Comment by idoybh** [comment]
> I'm not sure who to request to review lol Sorry if disturbed

You never disturb. And requested from the right member as well. Thanks

**Comment by gotenksIN** [comment]
yeah I dont know why los decided it was a good idea to add caf as well as upstream repos when aosp added support for sn100x on s

**Comment by ALKALiKong233** [comment]
> yeah I dont know why los decided it was a good idea to add caf as well as upstream repos when aosp added support for sn100x on s

Wait a sec AOSP added support for sn100x on S? I don't know that...

**Comment by gotenksIN** [comment]
> > yeah I dont know why los decided it was a good idea to add caf as well as upstream repos when aosp added support for sn100x on s
> 
> Wait a sec AOSP added support for sn100x on S? I don't know that...

https://github.com/xiaomi-sm8250-devs/android_device_xiaomi_sm8250-common/commit/bc00d9cd60a17c17ad8e2288677f0fd6848b2b92

**Comment by ALKALiKong233** [comment]
> > > yeah I dont know why los decided it was a good idea to add caf as well as upstream repos when aosp added support for sn100x on s
> > 
> > 
> > Wait a sec AOSP added support for sn100x on S? I don't know that...
> 
> [xiaomi-sm8250-devs/android_device_xiaomi_sm8250-common@bc00d9c](https://github.com/xiaomi-sm8250-devs/android_device_xiaomi_sm8250-common/commit/bc00d9cd60a17c17ad8e2288677f0fd6848b2b92)

K got it, thanks. Time to close this I think.

**Pull request closed without merging**
